name: Deploy Backend to EC2
on:
  push:
    branches: [ "main" ]
    paths:
      - 'server/backend/**'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /path/to/your/app/server/backend
            git pull origin main
            source venv/bin/activate
            pip install -r requirements.txt
            sudo systemctl restart your_backend_service
